vich_uploader:
  db_driver: orm

  mappings:
    profile:
      uri_prefix: /images/profiles
      upload_destination: "%kernel.project_dir%/public/images/profiles"
      namer: App\Vich\Naming\ImageNamer
