# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"
      - "../src/Tests/"
  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones

  App\Vich\Naming\ImageNamer:
    public: true

  App\Listener\AuthenticationSuccessListener:
    arguments: ["%lexik_jwt_authentication.token_ttl%"]
    tags:
      - {
          name: kernel.event_listener,
          event: lexik_jwt_authentication.on_authentication_success,
          method: onAuthenticationSuccess,
          priority: -2,
        }

  App\Listener\RefreshedTokenListener:
    arguments: ["%gesdinet_jwt_refresh_token.ttl%"]

  App\Listener\JWTNotFoundListener:
    tags:
      - {
          name: kernel.event_listener,
          event: lexik_jwt_authentication.on_jwt_not_found,
          method: onJWTNotFound,
          priority: 0,
        }

  App\Listener\CorsListener:
    tags:
      - { name: kernel.event_subscriber }

fos_rest:
  body_converter:
    enabled: true
    validate: true
    validation_errors_argument: violations
  view:
    formats: { json: true, xml: false, rss: false }
    view_response_listener: true
  serializer:
    serialize_null: true
  format_listener:
    rules:
      - { path: "^/", priorities: ["json"], fallback_format: "json" }
  exception:
    enabled: true
    codes:
      {
        App\Exception\ResourceValidationException: 400,
        App\Exception\ResourceNotFoundException: 204,
      }
